### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by Valdblade** [henkelmax/audio-player#31] opened 2023-02-23 00:14 UTC
**Bug description**

**Steps to reproduce the issue**
1. Go in-game server using Fabric
2. Use any of the audio player commands in order to have the song downloaded
3. Add the downloaded sound in the music disc at hand
4. Place disc in jukebox
5.  No sound playing

**Expected behavior**
Sound playing

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

https://pastebin.com/KfQiF5W5

**Versions**
- Minecraft version: 1.19.3
- Fabric loader version:  0.14.11
- Mod version 1.4.5 (latest)

**Other mods**
1.  Fabric API (client/server)
2.  Modmenu (client)
3.  Sodium (client)
4.  Sound Physics Remastered (client)
5.  Simple Voice Chat (client/server)
6.  Essential Commands (server) 
7.  Luck Perms (server) 

**Screenshots (Optional)**
Screenshots of the issue.

Below i am sedning a link to a screen recording of the issue 
https://drive.google.com/file/d/1VgnSaAikrcONkWJqnBp49tC8-dxXA6MJ/edit

**Comment by Valdblade** [comment] 2023-02-23 00:19
Also to add up it plays a sharp sound and then stops. Attaching screen recording of it:
https://drive.google.com/file/d/1BFDHt5uSD-8SYMAc47vOF5tRfBT5Oqzy

**Comment by henkelmax** [comment] 2023-02-23 08:33
Duplicate of #30

**Closed by henkelmax** 2023-02-23 08:33 UTC
Labels: bug
